apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis
    app: demo
spec:
  ports:
    - port: 6379
      targetPort: 6379
      name: redis
  selector:
    name: redis
    app: demo