version: '2'
services:
  mongodb:
    image: mongo
    restart: always
    networks:
      - bookstore

  goapp:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    restart: always
    networks:
      - bookstore


networks:
  bookstore:
    driver: bridge
