version: '2'
services:
  mongodb:
    image: mongo
    restart: always
    networks:
      - bookstore

  redis:
    image: redis
    restart: always
    networks: 
      - bookstore

  goapp:
    image: josemarjobs/multi-booksapp
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - bookstore


networks:
  bookstore:
    driver: bridge
