apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: demo
    env: test
spec:
  containers:
    - image: nginx
      name:  nginx
      ports:
        - name: http
          containerPort: 80
          protocol: TCP
    