apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  containers:
    - image: josemarjobs/booksapp
      name:  web
      ports:
      - containerPort: 3000
        name: http
        protocol: TCP