apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  ports:
    - port: 3000
      targetPort: 3000
      name: http
      protocol: TCP
  selector:
    name: web
  type: NodePort