apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
        - image: josemarjobs/booksapp
          name:  web
          ports:
          - name: http
            containerPort: 3000
            protocol: TCP