apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: demo
spec:
  containers:
    - image:  mongo
      name:  mongodb
      ports:
        - containerPort:  27017
          protocol: TCP