apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    name: mongodb
    app: demo
spec:
  ports:
    - port: 27017
      name: mongodb
      targetPort: 27017
  selector:
    name: mongodb
    app: demo