apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
          name: redis
          protocol: TCP
    - name: goapp
      image: josemarjobs/multi-booksapp
      env:
        - name: "REDIS_SERVER_URL"
          value: "localhost"
      ports:
        - containerPort: 5000
          name: http
          protocol: TCP