apiVersion: v1
kind: ReplicationController
metadata:
  name: web
  labels:
    name: web
    app: demo
spec:
  replicas: 5
  template: 
    metadata:
      labels:
        name: web
    spec:
      containers:
        - image: redis
          name: redis
          ports: 
            - containerPort: 6379
              name: redis
              protocol: TCP
        - image: josemarjobs/multi-booksapp
          name: goapp
          env:
            - name: "REDIS_SERVER_URL"
              value: "localhost"
          ports:
            - containerPort: 5000
              name: http
              protocol: TCP